### ISSUE TITLE
docker compose up --build: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by agardnerIT** [open-telemetry/opentelemetry-demo#1099]
# Bug Report

```
docker compose up --build
[+] Building 0.6s (0/1)
 => [internal] booting buildkit                                                                                                       0.6s 
 => => starting container buildx_buildkit_hopeful_wiles0                                                                              0.6s
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x1477298]

goroutine 43 [running]:
github.com/moby/buildkit/client.(*withTracerDelegate).SetSpanExporter(0x2787108?, {0x2787108?, 0xc00066a270?}, {0x2772cb0?, 0xc0005f6500?})
        <autogenerated>:1 +0x38
github.com/moby/buildkit/client.(*Client).setupDelegatedTracing(0x2787108?, {0x2787108, 0xc00066a270}, {0x276bfc0, 0xc000766f50})
        github.com/moby/buildkit@v0.10.4/client/client.go:168 +0x15c
github.com/moby/buildkit/client.New({0x2787108, 0xc00066a270}, {0x0, 0x0}, {0xc0006e7da0, 0x2, 0x2778520?})
        github.com/moby/buildkit@v0.10.4/client/client.go:156 +0x14da
github.com/docker/buildx/driver/docker-container.(*Driver).Client(0xc0006d7db8?, {0x2787108, 0xc00066a270})
        github.com/docker/buildx@v0.9.1/driver/docker-container/driver.go:362 +0x20a
github.com/docker/buildx/driver.(*cachedDriver).Client.func1()
        github.com/docker/buildx@v0.9.1/driver/manager.go:157 +0x32
sync.(*Once).doSlow(0xc0006d7e90?, 0x1689ff4?)
        sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        sync/once.go:65
github.com/docker/buildx/driver.(*cachedDriver).Client(0xc00051c000?, {0x2787108?, 0xc00066a270?})
        github.com/docker/buildx@v0.9.1/driver/manager.go:156 +0x65
github.com/docker/buildx/driver.Boot({0x2787060, 0xc00051c0c0}, {0x2787108, 0xc00066a270}, {0x2791308?, 0xc00051c000}, {0x2778490?, 0xc0005f6050})
        github.com/docker/buildx@v0.9.1/driver/driver.go:82 +0x151
github.com/docker/buildx/build.ensureBooted.func1.1()
        github.com/docker/buildx@v0.9.1/build/build.go:181 +0x77
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```

Commit: https://github.com/open-telemetry/opentelemetry-demo/commit/54aefe50f799812cc20972be3f82bcaf58811a3a

## Symptom

`docker compose up --build` fails in windows with above error.

**What is the expected behavior?**

`docker compose up --build` works and demo runs

What do you expect to see?

**What is the actual behavior?**

What did you see instead?

## Reproduce

- Pull the demo at the commit above
- Run `docker compose up --build` on Windows

## Docker Version

```
docker version
Client:
 Cloud integration: v1.0.31
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.18.10
 Git commit:        7155243
 Built:             Thu Jan 19 17:43:10 2023
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.17.1 (101757)
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:32:04 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

## Docker Compose Version

```
docker compose version
Docker Compose version v2.15.1
```

**Comment by mviitane** [comment]
Hi Adam, could you retry after updating your branch? There were some build problems before the v1.5 release, but at least I don't see any build problems currently when using the latest.

**Comment by puckpuck** [comment]
Closing this. If you still have issues with the latest release, please open a new issue.
