### ISSUE TITLE
docker compose up -d, version v1.5.0,  adservice、emailservice、postgres container start failed

### ISSUE THREAD

**Issue by yew1eb** [open-telemetry/opentelemetry-demo#1175]
# Bug Report

Which version of the demo you are using? 
fc01d8f46f9d2a1cac6a4e674662fbfe8b66f3c4

## Symptom
docker-compose up -d

 adservice、emailservice、postgres container start failed,  `docker ps` show follew:  
```
2a07a3da92ec        ghcr.io/open-telemetry/demo:1.5.0-adservice               "./build/install/ope…"   About an hour ago   Restarting (1) 29 seconds ago                                                                                                                        ad-service
520ffe0f26e2        ghcr.io/open-telemetry/demo:1.5.0-emailservice            "bundle exec ruby em…"   About an hour ago   Restarting (1) 6 seconds ago                                                                                                                         email-service
ce262aa244f1        postgres:16.0                                             "docker-entrypoint.s…"   About an hour ago   Restarting (1) 31 seconds ago                                                                                                                        postgres
```

**docker  logs：**

ad-service:
```
ERROR: JAVA_HOME is set to an invalid directory: /opt/java/openjdk

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

email-service:
```
== Sinatra has ended his set (crowd applauds)
/usr/local/bundle/gems/puma-6.3.0/lib/puma/reactor.rb:37:in `initialize': can't create Thread: Operation not permitted (ThreadError)
	from /usr/local/bundle/gems/puma-6.3.0/lib/puma/reactor.rb:37:in `new'
	from /usr/local/bundle/gems/puma-6.3.0/lib/puma/reactor.rb:37:in `run'
	from /usr/local/bundle/gems/puma-6.3.0/lib/puma/server.rb:249:in `run'
	from /usr/local/bundle/gems/puma-6.3.0/lib/puma/single.rb:53:in `run'
	from /usr/local/bundle/gems/puma-6.3.0/lib/puma/launcher.rb:194:in `run'
	from /usr/local/bundle/gems/puma-6.3.0/lib/rack/handler/puma.rb:76:in `run'
	from /usr/local/bundle/gems/sinatra-3.0.6/lib/sinatra/base.rb:1593:in `start_server'
	from /usr/local/bundle/gems/sinatra-3.0.6/lib/sinatra/base.rb:1532:in `run!'
	from /usr/local/bundle/gems/sinatra-3.0.6/lib/sinatra/main.rb:47:in `block in <module:Sinatra>'
== Sinatra (v3.0.6) has taken the stage on 6060 for production with backup from Puma
E, [2023-10-13T04:19:46.954642 #1] ERROR -- : OpenTelemetry error: unexpected error in BatchSpanProcessor#reset_on_fork - can't create Thread: Operation not permitted
I, [2023-10-13T04:19:46.958371 #1]  INFO -- : Instrumentation: OpenTelemetry::Instrumentation::Sinatra was successfully installed with the following options {}
Puma starting in single mode...
* Puma version: 6.3.0 (ruby 3.1.4-p223) ("Mugi No Toki Itaru")
*  Min threads: 0
*  Max threads: 5
*  Environment: production
*          PID: 1
* Listening on http://0.0.0.0:6060
```

postgres:
```
popen failure: Cannot allocate memory
initdb: error: program "postgres" is needed by initdb but was not found in the same directory as "/usr/lib/postgresql/16/bin/initdb"
popen failure: Cannot allocate memory
initdb: error: program "postgres" is needed by initdb but was not found in the same directory as "/usr/lib/postgresql/16/bin/initdb"
popen failure: Cannot allocate memory
initdb: error: program "postgres" is needed by initdb but was not found in the same directory as "/usr/lib/postgresql/16/bin/initdb"
popen failure: Cannot allocate memory
initdb: error: program "postgres" is needed by initdb but was not found in the same directory as "/usr/lib/postgresql/16/bin/initdb"
```

**What is the expected behavior?**

What do you expect to see?

**What is the actual behavior?**

What did you see instead?

## Reproduce
system:
```
root@ubuntu:~# lsb_release  -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```
docker version:
```
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Fri Dec 18 12:15:19 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Fri Dec  4 23:02:49 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2.2
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
```

docker-compose version:
```
Docker Compose version v2.22.0
```

We will close this issue if:

* The steps you provided are complex.
* If we can not reproduce the behavior you're reporting.

**Comment by puckpuck** [comment]
Please use `docker compose` which is not the same as `docker-compose`.

**Comment by yew1eb** [comment]
@puckpuck using `docker compose`, same issue again.

**Comment by puckpuck** [comment]
How much free memory does this system have?

**Comment by yew1eb** [comment]
@puckpuck 
```
root@ubuntu:~# free -h
              total        used        free      shared  buff/cache   available
Mem:           62Gi       3.5Gi        44Gi       284Mi        14Gi        57Gi
Swap:            0B          0B          0B
```

**Comment by yew1eb** [comment]
fixed `postgres` conatiner start fail, use image version `postgres:16-alpine` replace ` postgres:16`.
but `ad-service` and `email-service` still can't started.

**Comment by puckpuck** [comment]
This feels like an isuse with the host or docker version, not the demo images themselves.

When you run `docker compose version` what output do you get?
