### ISSUE TITLE
[grafana] Broken dashboards

### ISSUE THREAD

**Issue by julianocosta89** [open-telemetry/opentelemetry-demo#1771]
# Bug Report

Which version of the demo you are using?
09ab6cc6f669592507d8d4590fc46dcf7dddeb1c

## Symptom

Start the demo, navigate to <http://localhost:8080/grafana> and check the demo dashboards.

**What is the expected behavior?**

I expect the demo dashboards to be populated with data.

**What is the actual behavior?**

No data is shown and a couple of error messages are raised in some tiles.

## Reproduce

Could you provide the minimum required steps to resolve the issue you're seeing?

```
make start
```

**Comment by julianocosta89** [comment]
Services not loaded:
![image](https://github.com/user-attachments/assets/77bb0f6b-9944-49a0-83bd-6d6e0eaf3b6b)

Tiles with error messages:
![image](https://github.com/user-attachments/assets/62baeaef-f81c-421f-92e1-7b31ae829dee)


Error msg:
```
An unexpected error happened
Details
Error: id field is required for nodes data frame.

    at tt (http://localhost:8080/grafana/public/build/5511.448e6d990cb888c8419c.js:104:36)
    at div
    at j (http://localhost:8080/grafana/public/build/nodeGraphPanel.f3cf4eaaa80ab54d2e6f.js:1:237)
    at r (http://localhost:8080/grafana/public/build/322.9e448e90c86f8dd2907e.js:1:518)
    at g (http://localhost:8080/grafana/public/build/322.9e448e90c86f8dd2907e.js:12:133441)
    at i (http://localhost:8080/grafana/public/build/322.9e448e90c86f8dd2907e.js:12:133950)
    at div
    at section
    at M (http://localhost:8080/grafana/public/build/322.9e448e90c86f8dd2907e.js:32:26269)
    at div
    at div
    at d_ (http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:39:328501)
    at Jt (http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:39:138778)
    at Component (http://localhost:8080/grafana/public/build/322.9e448e90c86f8dd2907e.js:278:32195)
    at Jt (http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:39:138778)
    at div
    at http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:39:384412
    at http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:39:387096
    at M (http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:277:3224)
    at N (http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:250:13218)
    at b (http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:256:5130)
    at div
    at N (http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:256:14206)
    at div
    at div
    at q0 (http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:39:386050)
    at Jt (http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:39:138778)
    at Component (http://localhost:8080/grafana/public/build/322.9e448e90c86f8dd2907e.js:308:5439)
    at Jt (http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:39:138778)
    at div
    at div
    at div
    at n (http://localhost:8080/grafana/public/build/322.9e448e90c86f8dd2907e.js:159:37362)
    at div
    at X (http://localhost:8080/grafana/public/build/322.9e448e90c86f8dd2907e.js:194:22907)
    at Yn (http://localhost:8080/grafana/public/build/322.9e448e90c86f8dd2907e.js:278:51310)
    at Jt (http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:39:138778)
    at z0 (http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:39:381316)
    at In (http://localhost:8080/grafana/public/build/8779.5dae8c32eee2bd40de3c.js:1:2522)
    at Xo (http://localhost:8080/grafana/public/build/8779.5dae8c32eee2bd40de3c.js:51:32923)
    at Suspense
    at g (http://localhost:8080/grafana/public/build/322.9e448e90c86f8dd2907e.js:12:133441)
    at th (http://localhost:8080/grafana/public/build/322.9e448e90c86f8dd2907e.js:2378:39173)
    at tt (http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:295:25340)
    at Re (http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:295:4574)
    at ot (http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:295:12212)
    at zt (http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:286:18055)
    at tt (http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:295:27534)
    at div
    at http://localhost:8080/grafana/public/build/3719.c065b2e146c4c8347d51.js:1:135436
    at main
    at div
    at div
    at div
    at Pf (http://localhost:8080/grafana/public/build/322.9e448e90c86f8dd2907e.js:2380:4677)
    at Af (http://localhost:8080/grafana/public/build/322.9e448e90c86f8dd2907e.js:2380:9995)
    at Re (http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:295:4574)
    at ot (http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:295:12212)
    at Ke (http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:295:11545)
    at un (http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:286:18357)
    at y (http://localhost:8080/grafana/public/build/322.9e448e90c86f8dd2907e.js:5:188596)
    at tt (http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:295:21503)
    at Kc (http://localhost:8080/grafana/public/build/322.9e448e90c86f8dd2907e.js:2380:11398)
    at div
    at Xl (http://localhost:8080/grafana/public/build/322.9e448e90c86f8dd2907e.js:2378:18744)
    at y (http://localhost:8080/grafana/public/build/3379.020d2edcd8eb1d9f6d9a.js:151:9173)
    at C (http://localhost:8080/grafana/public/build/4239.c2eca2b0222ddf40980b.js:183:17550)
    at d (http://localhost:8080/grafana/public/build/3719.c065b2e146c4c8347d51.js:24:12171)
    at g (http://localhost:8080/grafana/public/build/322.9e448e90c86f8dd2907e.js:12:133441)
    at i (http://localhost:8080/grafana/public/build/3
```

**Comment by i--storm** [comment]
I have the same issue

**Comment by alessio-locatelli** [comment]
Still a problem... or a problem again. 

![Image](https://github.com/user-attachments/assets/61cc0d11-5c63-40b2-934f-eb732b8bd7c0)

@puckpuck can you or someone else reopen this issue?

**Comment by julianocosta89** [comment]
@alessio-locatelli Thanks for reporting it, I've re-opened it 😢

**Comment by puckpuck** [comment]
I just tried this again. Initially, you get no data. After waiting 5 minutes, however, I can see data start to show up in all dashboards. Can you run for more than 5 minutes before checking?

 If it works after 5 minutes, we should update our docs and the `make start` output.

**Comment by puckpuck** [comment]
Though data is flowing in the vast majority of panels, I have noticed that we have a couple of broken panels across all the dashboards. I'll make a PR to update these panels.

![Image](https://github.com/user-attachments/assets/bcc5752f-832f-48b1-8eca-471eda1a245b)
