### ISSUE TITLE
Checkout service not starting successfully when using Docker compose deployment

### ISSUE THREAD

**Issue by saurabhdes** [open-telemetry/opentelemetry-demo#1874]
# Bug Report

Which version of the demo you are using? (please provide either a specific
[[7543c59](https://github.com/open-telemetry/opentelemetry-demo/commit/7543c595d9e43cda0433bf8461940022152f302f)]

## Symptom

Checkout service not starting successfully when using Docker compose deployment. It keeps restarting.

**What is the expected behavior?**
Checkout service starts successfully

**What is the actual behavior?**
`2024-12-28 14:52:24 goroutine 1 [running]:
2024-12-28 14:52:24 main.mustMapEnv(0x400030c8f0, {0xbe3efb, 0x15})
2024-12-28 14:52:24     /usr/src/app/main.go:229 +0xb8
2024-12-28 14:52:24 main.main()
2024-12-28 14:52:24     /usr/src/app/main.go:170 +0x230
2024-12-28 14:52:37 panic: environment variable "SHIPPING_SERVICE_ADDR" not set`

## Reproduce

https://opentelemetry.io/docs/demo/docker-deployment/
make start
Go to Docker Desktop > Opentelemetery Docker compose stack > checkout service logs and notice the above mentioned error message displayed and checkout service keeps restarting.

**Comment by CharlieTLe** [comment]
This was updated recently in https://github.com/open-telemetry/opentelemetry-demo/commit/fca8fd1374081a3df2699f08cf5784dab16919a3.

Running `make start` will pull a tagged image, but there hasn't been a release since https://github.com/open-telemetry/opentelemetry-demo/pull/1763 to update the images.

Can you try running `make redeploy service=checkoutservice` until a new release is published?

cc: @julianocosta89

**Comment by saurabhdes** [comment]
thanks @CharlieTLe for the workaround. I deployed checkoutservice with the command you suggested and now it's running fine.
