### ISSUE TITLE
Cart-Service need more helpful log / status check

### ISSUE THREAD

**Issue by wph95** [open-telemetry/opentelemetry-demo#223]
used wrong env `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT`, cart-service can't connect to OTLP
**but no error log**

```
➜  charts git:(wph95/otel-demo) ✗ kc logs demo-cart-service-57f754d46f-hmj7m
Connecting to Redis: demo-redis:6379,ssl=false,allowAdmin=true,abortConnect=false
Successfully connected to Redis
Performing small test
Small test result: OK
Initialization completed
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:8080
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /usr/src/app
Connection failed. Disposing the object
Connection failed. Disposing the object
Connection to redis was retored successfully
Connection to redis was retored successfully
GetCartAsync called with userId=0685aee7-b2b7-47c3-893a-ae4b898138f0
AddItemAsync called with userId=0685aee7-b2b7-47c3-893a-ae4b898138f0, productId=1YMWWN1N4O, quantity=1
GetCartAsync called with userId=0685aee7-b2b7-47c3-893a-ae4b898138f0
```

used right env `OTEL_EXPORTER_OTLP_ENDPOINT`, connect to OTLP
```
➜  charts git:(wph95/otel-demo) ✗ kc logs demo-cart-service-57f754d46f-hmj7m
Connecting to Redis: demo-redis:6379,ssl=false,allowAdmin=true,abortConnect=false
Successfully connected to Redis
Performing small test
Small test result: OK
Initialization completed
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:8080
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /usr/src/app
Connection failed. Disposing the object
Connection failed. Disposing the object
Connection to redis was retored successfully
Connection to redis was retored successfully
GetCartAsync called with userId=0685aee7-b2b7-47c3-893a-ae4b898138f0
AddItemAsync called with userId=0685aee7-b2b7-47c3-893a-ae4b898138f0, productId=1YMWWN1N4O, quantity=1
GetCartAsync called with userId=0685aee7-b2b7-47c3-893a-ae4b898138f0


```

**Comment by wph95** [comment]
might improve LogLevel ?

**Comment by cartersocha** [comment]
@mic-max could you potentially take a look when youre back?

**Comment by cijothomas** [comment]
Logging is done with plain Console log statements. It should be using the Logging API. I can make a small PR attempt...

**Comment by yuxiaoba** [comment]
@cijothomas  hello, cijothomas! Recently , I try to using the `opentelemetry` logging API to print logs for  `cartservice`.

I first config `opentelemetry `  log in [program.cs](https://github.com/yuxiaoba/opentelemetry-demo/blob/main/src/cartservice/src/Program.cs#L67)

```
builder.Logging.ClearProviders();

builder.Logging.AddOpenTelemetry(options =>
{
    options.ConfigureResource(r => r.AddTelemetrySdk());
    options.AddConsoleExporter();
});

builder.Services.Configure<OpenTelemetryLoggerOptions>(opt =>
{
    opt.IncludeScopes = true;
    opt.ParseStateValues = true;
    opt.IncludeFormattedMessage = true;
});

builder.Services.AddGrpc();
builder.Services.AddGrpcHealthChecks()
    .AddCheck("Sample", () => HealthCheckResult.Healthy());
```

Then I init logs in [RedisCartStore.cs](https://github.com/yuxiaoba/opentelemetry-demo/blob/main/src/cartservice/src/cartstore/RedisCartStore.cs#L39)

```

        private readonly ILogger<RedisCartStore> log;

        public RedisCartStore(ILogger<RedisCartStore> logger)
        {
            log = logger;
        }


```

Finally, I logs the [AddItemAsync  call](https://github.com/yuxiaoba/opentelemetry-demo/blob/main/src/cartservice/src/cartstore/RedisCartStore.cs#L126)
```
 log.LogInformation("AddItemAsync called with userId={userId}, productId={productId}, quantity={quantity}", userId, productId, quantity)
```

I can compile this code and running it, but I meet some error in log
```
LogRecord.Timestamp:               2022-11-10T06:30:02.6120211Z
LogRecord.TraceId:                 281311f89567e856aae2042f92b21b5a
LogRecord.SpanId:                  9797adee538b6ac9
LogRecord.TraceFlags:              Recorded
LogRecord.CategoryName:            Grpc.AspNetCore.Server.ServerCallHandler
LogRecord.LogLevel:                Error
LogRecord.FormattedMessage:        Error when executing service method 'AddItem'.
LogRecord.StateValues (Key:Value):
    ServiceMethod: AddItem
    OriginalFormat (a.k.a Body): Error when executing service method '{ServiceMethod}'.
LogRecord.EventId:                 6
LogRecord.EventName:               ErrorExecutingServiceMethod
LogRecord.Exception:               System.ArgumentNullException: Value cannot be null. (Parameter 'logger')
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger , LogLevel , EventId , Exception , String , Object[] )
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger , LogLevel , String , Object[] )
   at Microsoft.Extensions.Logging.LoggerExtensions.LogInformation(ILogger , String , Object[] )
   at cartservice.cartstore.RedisCartStore.AddItemAsync(String userId, String productId, Int32 quantity) in /usr/src/app/cartstore/RedisCartStore.cs:line 128
   at cartservice.services.CartService.AddItem(AddItemRequest request, ServerCallContext context) in /usr/src/app/services/CartService.cs:line 40
   at Grpc.Shared.Server.UnaryServerMethodInvoker`3.AwaitInvoker(Task`1 , GrpcActivatorHandle`1 )
   at Grpc.Shared.Server.UnaryServerMethodInvoker`3.AwaitInvoker(Task`1 , GrpcActivatorHandle`1 )
   at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext , HttpContextServerCallContext )
   at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext , Method`2 , Task )
LogRecord.ScopeValues (Key:Value):
[Scope.0]:SpanId: 9797adee538b6ac9
[Scope.0]:TraceId: 281311f89567e856aae2042f92b21b5a
[Scope.0]:ParentId: e671d5bcbe789f95
[Scope.1]:ConnectionId: 0HMM2SJM9SJH0
[Scope.2]:RequestId: 0HMM2SJM9SJH0:0000000B
[Scope.2]:RequestPath: /hipstershop.CartService/AddItem
```

Can you give me some suggestion for me to fix this error, I would like to contribute this project.

**Comment by austinlparker** [comment]
This will be addressed in future logging work - closing for now.
