### ISSUE TITLE
[featureflag] UI fails to load on M1 Mac - (Postgrex.Error) ERROR 42P01 (undefined_table) relation "featureflags" does not exist

### ISSUE THREAD

**Issue by mviitane** [open-telemetry/opentelemetry-demo#294]
# Bug Report

## Which version of the demo you are using? 
main/latest 
commit 1a4698f958622a798122fda3ac532938c6a93128

## Environment:
Kernel Version 21.6.0
RELEASE_ARM64_T6000 arm64
Docker Desktop 4.8.1

## Symptom

Feature flag UI doesn't load: "Internal Server Error"
http://localhost:8081/

Each reload produces the following log:
```
10:13:08.686 request_id=FwqRUMKG7L0YbksAAARB [info] GET /
10:13:08.693 request_id=FwqRUMKG7L0YbksAAARB [info] Sent 500 in 7ms
10:13:08.693 [error] #PID<0.2009.0> running FeatureflagserviceWeb.Endpoint (connection #PID<0.2008.0>, stream id 1) terminated
Server: localhost:8081 (http)
Request: GET /
** (exit) an exception was raised:
    ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "featureflags" does not exist

    query: SELECT f0."id", f0."description", f0."enabled", f0."name", f0."inserted_at", f0."updated_at" FROM "featureflags" AS f0
        (ecto_sql 3.8.2) lib/ecto/adapters/sql.ex:932: Ecto.Adapters.SQL.raise_sql_call_error/1
        (ecto_sql 3.8.2) lib/ecto/adapters/sql.ex:847: Ecto.Adapters.SQL.execute/6
        (ecto 3.8.3) lib/ecto/repo/queryable.ex:221: Ecto.Repo.Queryable.execute/4
        (ecto 3.8.3) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
        (featureflagservice 0.1.0) lib/featureflagservice_web/controllers/page_controller.ex:7: FeatureflagserviceWeb.PageController.index/2
        (featureflagservice 0.1.0) lib/featureflagservice_web/controllers/page_controller.ex:1: FeatureflagserviceWeb.PageController.action/2
        (featureflagservice 0.1.0) lib/featureflagservice_web/controllers/page_controller.ex:1: FeatureflagserviceWeb.PageController.phoenix_controller_pipeline/2
        (phoenix 1.6.9) lib/phoenix/router.ex:354: Phoenix.Router.__call__/2
10:13:08.711 request_id=FwqRUMQIP1HPNQQAAASB [info] GET /null
10:13:08.711 request_id=FwqRUMQIP1HPNQQAAASB [info] Sent 404 in 314µs
```

## Reproduce

$ docker compose up
http://localhost:8081/

## Additional Context

Fails only on M1 Mac. Seems to be working fine on Ubuntu 22.04 LTS, x86_64.

**Comment by puckpuck** [comment]
This was fixed by #315
