### ISSUE TITLE
Cypress e2e tests fails to start

### ISSUE THREAD

**Issue by mviitane** [open-telemetry/opentelemetry-demo#305]
# Bug Report

## Which version of the demo you are using? 
main/latest
commit bbf842581a9e99ac4475b760f89796b460c5de67

## Symptom

```
$ docker compose run frontendTests
[+] Running 13/0
 ⠿ Container redis-cart               Running                                                                                                                                                                             0.0s
 ⠿ Container jaeger                   Running                                                                                                                                                                             0.0s
 ⠿ Container otel-col                 Running                                                                                                                                                                             0.0s
 ⠿ Container ad-service               Running                                                                                                                                                                             0.0s
 ⠿ Container currency-service         Running                                                                                                                                                                             0.0s
 ⠿ Container payment-service          Running                                                                                                                                                                             0.0s
 ⠿ Container email-service            Running                                                                                                                                                                             0.0s
 ⠿ Container shipping-service         Running                                                                                                                                                                             0.0s
 ⠿ Container product-catalog-service  Running                                                                                                                                                                             0.0s
 ⠿ Container recommendation-service   Running                                                                                                                                                                             0.0s
 ⠿ Container cart-service             Running                                                                                                                                                                             0.0s
 ⠿ Container checkout-service         Running                                                                                                                                                                             0.0s
 ⠿ Container frontend                 Created                                                                                                                                                                             0.0s
[+] Running 1/1
 ⠿ Container frontend  Started                                                                                                                                                                                            0.3s
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[228:0816/072314.864197:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[228:0816/072314.865737:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
Your configFile is invalid: /cypress/cypress.config.ts

It threw an error when required, check the stack trace below:

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /cypress/cypress.config.ts
    at new NodeError (node:internal/errors:371:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:87:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:102:38)
    at defaultLoad (node:internal/modules/esm/load:21:14)
    at ESMLoader.load (node:internal/modules/esm/loader:359:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:58)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:297:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:261:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async loadFile (/root/.cache/Cypress/10.3.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:106:14)
    at async EventEmitter.<anonymous> (/root/.cache/Cypress/10.3.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:116:32)
```

```
$ docker compose run integrationTests
[+] Running 12/0
 ⠿ Container redis-cart               Running                                                                                                                                                                             0.0s
 ⠿ Container jaeger                   Running                                                                                                                                                                             0.0s
 ⠿ Container otel-col                 Running                                                                                                                                                                             0.0s
 ⠿ Container currency-service         Running                                                                                                                                                                             0.0s
 ⠿ Container ad-service               Running                                                                                                                                                                             0.0s
 ⠿ Container cart-service             Running                                                                                                                                                                             0.0s
 ⠿ Container email-service            Running                                                                                                                                                                             0.0s
 ⠿ Container payment-service          Running                                                                                                                                                                             0.0s
 ⠿ Container product-catalog-service  Running                                                                                                                                                                             0.0s
 ⠿ Container recommendation-service   Running                                                                                                                                                                             0.0s
 ⠿ Container shipping-service         Running                                                                                                                                                                             0.0s
 ⠿ Container checkout-service         Running                                                                                                                                                                             0.0s

> test@1.0.0 test
> ava

sh: ava: not found

```

**What do you expect to see?**

It seems there are some prerequisites in order to get these tests running.

@xoscar I propose to add simple documentation into test/README.md to cover the possible prerequisites and also to include the actual commands to start the tests.

Related to #298

**Comment by xoscar** [comment]
Hey @mviitane thanks for taking a look. I'll be working on this today
