### ISSUE TITLE
[featureflag] featureflag failed to start

### ISSUE THREAD

**Issue by Frapschen** [open-telemetry/opentelemetry-demo#364]
# Bug Report

Which version of the demo you are using? 

0.3.4-alpha

## Symptom

I use helm to install the demo, the featureflag service failed to start and print this logs:
```
ERROR! Config provider Config.Reader failed with:

 ** (ArgumentError) errors were found at the given arguments:

 

   * 1st argument: not a binary

 

     :erlang.binary_to_integer(nil)

     (stdlib 4.0) erl_eval.erl:744: :erl_eval.do_apply/7

     (stdlib 4.0) erl_eval.erl:492: :erl_eval.expr/6

     (elixir 1.13.3) src/elixir.erl:296: :elixir.recur_eval/3

     (elixir 1.13.3) src/elixir.erl:274: :elixir.eval_forms/3

     (elixir 1.13.3) lib/code.ex:404: Code.validated_eval_string/3

     (elixir 1.13.3) lib/config.ex:260: Config.__eval__!/3

     (elixir 1.13.3) lib/config/reader.ex:92: Config.Reader.read!/2

 

 {"init terminating in do_boot",{badarg,[{erlang,binary_to_integer,[nil],[{error_info,#{module=>erl_erts_errors}}]},{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,744}]},{erl_eval,expr,6,[{file,"erl_eval.erl"},{line,492}]},{elixir,recur_eval,3,[{file,"src/elixir.erl"},{line,296}]},{elixir,eval_forms,3,[{file,"src/elixir.erl"},{line,274}]},{'Elixir.Code',validated_eval_string,3,[{file,"lib/code.ex"},{line,404}]},{'Elixir.Config','__eval__!',3,[{file,"lib/config.ex"},{line,260}]},{'Elixir.Config.Reader','read!',2,[{file,"lib/config/reader.ex"},{line,92}]}]}}

 init terminating in do_boot ({badarg,[{erlang,binary_to_integer,[nil],[{_}]},{erl_eval,do_apply,7,[{_},{_}]},{erl_eval,expr,6,[{_},{_}]},{elixir,recur_eval,3,[{_},{_}]},{elixir,eval_forms,3,[{_},{_}]},{Elixir.Code,validated_eval_string,3,[{_},{_}]},{Elixir.Config,__eval__!,3,[{_},{_}]},{Elixir.Config.Reader,read!,2,[{_},{_}]}]})

 

 Crash dump is being written to: erl_crash.dump...done
```

env:
kube version: v1.21.5
os: Linux 3.10.0-1160.6.1.el7.x86_64

**Comment by julianocosta89** [comment]
@puckpuck I believe that is the same issue @mviitane mentioned in the #362

**Comment by puckpuck** [comment]
🤔 I wonder if the 0.3.4-alpha feature flag service image we released is correct. WTAL.

**Comment by cartersocha** [comment]
I think this was solved by @joshleecreates with an auto recreate of a failed container. https://github.com/open-telemetry/opentelemetry-demo/pull/402
