### ISSUE TITLE
Error in console when attempting to checkout through frontend

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-demo#524]
# Bug Report

0.7.0-beta

## Symptom

When attempting to check out through the frontend, clicking the 'Place order' button causes the following:
```
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (checkout, line 0)
Unhandled Promise rejection: – "JSON Parse error: Unexpected identifier \"Internal\"" – "; Zone:" – "<root>" – "; Task:" – "Promise.then" – "; Value:" (2)
SyntaxError: JSON Parse error: Unexpected identifier "Internal" — _app-51ff14db9a601587.js:6:3346
"parse@[native code]
@http://localhost:8080/_next/static/chunks/pages/_app-51ff14db9a601587.js:6:3345
u@http://localhost:8080/_next/static/chunks/main-818050cf9ea3098e.js:1:94521
@http://localhost:8080/_next/static/chunks/main-818050cf9ea3098e.js:1:95804
d@http://localhost:8080/_next/static/chunks/pages/_app-51ff14db9a601587.js:13:79000
e@http://localhost:8080/_next/static/chunks/pages/_app-51ff14db9a601587.js:13:79198
run@http://localhost:8080/_next/static/chunks/434.5d13c09717162b96.js:1:4235
@http://localhost:8080/_next/static/chunks/434.5d13c09717162b96.js:19:2728
runTask@http://localhost:8080/_next/static/chunks/434.5d13c09717162b96.js:1:4846
@http://localhost:8080/_next/static/chunks/pages/_app-51ff14db9a601587.js:6:169210
w@http://localhost:8080/_next/static/chunks/434.5d13c09717162b96.js:1:11424
promiseReactionJob@[native code]"
```

Logs for frontend service:

```
Error: 13 INTERNAL: failed to charge card: could not charge the card: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup paymentservice on 127.0.0.11:53: no such host"
    at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:189:52)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 13,
  details: 'failed to charge card: could not charge the card: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup paymentservice on 127.0.0.11:53: no such host"',
  metadata: Metadata {
    internalRepr: Map(1) { 'content-type' => [Array] },
    options: {}
  }
}
Error: 14 UNAVAILABLE: No connection established
    at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:189:52)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 14,
  details: 'No connection established',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
```

Maybe this is just config related, but it seems like frontend server isn't able to connect to the payment service.

**Comment by austinlparker** [comment]
It seems like this is due to the payment service failing to start.
