### ISSUE TITLE
some  services CrashLoopBackOff  locally built images  on M1 mac with Rancher Desktop 1.7.0 with k8s 1.25.4,  dockerd, and Traefik disabled. 

### ISSUE THREAD

**Issue by lakamsani** [open-telemetry/opentelemetry-demo#686]
# Bug Report

via helm `helm list -n otel-demo`

opentelemetry-demo-0.15.4	1.2.1

## Symptom

A few of the services are not starting up.  Here's are some logs: 

```
➜  opentelemetry-demo git:(main) k get po -n otel-demo
NAME                                                      READY   STATUS             RESTARTS          AGE
vamsee-otel-demo-jaeger-57586587f5-d5t6j                  1/1     Running            1 (24m ago)       2d17h
vamsee-otel-demo-quoteservice-7d87598999-b4qrz            1/1     Running            1 (24m ago)       2d17h
vamsee-otel-demo-grafana-56b79fc744-zdzt4                 1/1     Running            1 (24m ago)       2d17h
vamsee-otel-demo-currencyservice-69cdb695f8-t5sq9         1/1     Running            1 (24m ago)       2d17h
vamsee-otel-demo-recommendationservice-d5cfd68f9-fpzb5    1/1     Running            1 (24m ago)       2d17h
vamsee-otel-demo-emailservice-65668f9dd9-2wvv9            1/1     Running            1 (24m ago)       2d17h
vamsee-otel-demo-ffspostgres-56698cc45f-4bprx             1/1     Running            1 (24m ago)       2d17h
vamsee-otel-demo-shippingservice-9cf56b5f-bklk4           1/1     Running            1 (24m ago)       2d17h
vamsee-otel-demo-otelcol-cbd74c44d-9rvhx                  1/1     Running            14 (24m ago)      2d14h
vamsee-otel-demo-redis-8d94cbf6c-rswlz                    1/1     Running            1 (24m ago)       2d17h
vamsee-otel-demo-prometheus-server-75457c85cd-qv7kx       1/1     Running            1 (24m ago)       2d17h
vamsee-otel-demo-loadgenerator-56bd8684c-88tcq            1/1     Running            73 (22m ago)      2d17h
vamsee-otel-demo-adservice-558fd5849f-wksb6               1/1     Running            5 (21m ago)       2d17h
vamsee-otel-demo-kafka-58fb4985c-fzqlt                    1/1     Running            21 (5m16s ago)    2d17h
vamsee-otel-demo-frontendproxy-74cff4fc-2b7w5             0/1     CrashLoopBackOff   553 (2m32s ago)   2d14h
vamsee-otel-demo-paymentservice-854b95679b-v9qcq          0/1     CrashLoopBackOff   590 (2m33s ago)   2d17h
vamsee-otel-demo-productcatalogservice-749bfcc6d7-5sjhw   0/1     CrashLoopBackOff   542 (2m20s ago)   2d14h
vamsee-otel-demo-checkoutservice-5c6d4bbb49-v2v98         0/1     CrashLoopBackOff   590 (2m20s ago)   2d17h
vamsee-otel-demo-featureflagservice-5d6dff984-hmgm5       0/1     CrashLoopBackOff   552 (2m17s ago)   2d14h
vamsee-otel-demo-accountingservice-66c7b6d7bb-zjzl6       0/1     CrashLoopBackOff   555 (2m10s ago)   2d14h
vamsee-otel-demo-frontend-65dbb5fdcd-9k22d                0/1     CrashLoopBackOff   544 (93s ago)     2d14h
vamsee-otel-demo-frauddetectionservice-7cb64f6759-q9tm7   0/1     CrashLoopBackOff   11 (72s ago)      2d17h
vamsee-otel-demo-cartservice-6c447dbd8b-fjcd5             0/1     CrashLoopBackOff   524 (44s ago)     2d14h
```

sometimes the error is `OOMKilled`, sometimes it is `CrashLoopBackOff` 
k8s has plenty of memory as shown by 

```
➜  opentelemetry-demo git:(main) k top node
NAME                   CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
lima-rancher-desktop   3156m        78%    4305Mi          36%
```

Not much in the logs for example: 

```
➜  opentelemetry-demo git:(main) k logs vamsee-otel-demo-productcatalogservice-749bfcc6d7-5sjhw -n otel-demo
➜  opentelemetry-demo git:(main) <----- prints nothing
```

**What is the expected behavior?**

All the services should be running. However these don't run. 

```
vamsee-otel-demo-frontendproxy-74cff4fc-2b7w5             0/1     CrashLoopBackOff   553 (2m32s ago)   2d14h
vamsee-otel-demo-paymentservice-854b95679b-v9qcq          0/1     CrashLoopBackOff   590 (2m33s ago)   2d17h
vamsee-otel-demo-productcatalogservice-749bfcc6d7-5sjhw   0/1     CrashLoopBackOff   542 (2m20s ago)   2d14h
vamsee-otel-demo-checkoutservice-5c6d4bbb49-v2v98         0/1     CrashLoopBackOff   590 (2m20s ago)   2d17h
vamsee-otel-demo-featureflagservice-5d6dff984-hmgm5       0/1     CrashLoopBackOff   552 (2m17s ago)   2d14h
vamsee-otel-demo-accountingservice-66c7b6d7bb-zjzl6       0/1     CrashLoopBackOff   555 (2m10s ago)   2d14h
vamsee-otel-demo-frontend-65dbb5fdcd-9k22d                0/1     CrashLoopBackOff   544 (93s ago)     2d14h
vamsee-otel-demo-frauddetectionservice-7cb64f6759-q9tm7   0/1     CrashLoopBackOff   11 (72s ago)      2d17h
vamsee-otel-demo-cartservice-6c447dbd8b-fjcd5             0/1     CrashLoopBackOff   524 (44s ago)     2d14h
```

## Reproduce

Problem is on : Apple M1 MacBook, Rancher desktop 1.7.0 with k8s 1.25.4,  dockerd, and Traefik disabled. 

## Additional Context

Collector config has been updated to send to Lightstep using info in this [blog](https://blog.devgenius.io/running-opentelemetry-demo-app-in-kubernetes-95dccd613e0b). 
and some minor updates as shown [here](https://gist.github.com/lakamsani/c329f211bf2a6f3d1c685ae02d4ff828) for the `values-ls.yaml` file . Verified that the secret has correct token. Same setup works in  in a lab cluster we have with k3s on a few ubuntu VMs.

**Comment by lakamsani** [comment]
just read that the helm charts don't support `arm64` https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-demo#prerequisites . Will try update the chart locally to use locally built images. Closing this.

**Comment by lakamsani** [comment]
Tried by building all the containers locally. Looks better except for the `featureflagservice`  which is `CrashLoopBackoff` with no logs.  See attached.  Any one have it working on a M1 with either `docker compose` or in a local k8s like Rancher? Error with `docker-compose up --pull missing` looks like this: 

```
➜  opentelemetry-demo git:(main) docker-compose up --pull missing
WARN[0000] container f5c13c325911f7997fa1543c20a804b28475a1ce1b7a11a77a40a31c1af19cbc is missing com.docker.compose.container-number label
WARN[0000] container f5c13c325911f7997fa1543c20a804b28475a1ce1b7a11a77a40a31c1af19cbc has invalid com.docker.compose.container-number label:
WARN[0000] container 3afa9af30e97d070786efb02f0143ccf9005fc46af86c5880647e740e3d7b88b is missing com.docker.compose.container-number label
WARN[0000] container 3afa9af30e97d070786efb02f0143ccf9005fc46af86c5880647e740e3d7b88b has invalid com.docker.compose.container-number label:
[+] Running 1/0
 ⠿ Network opentelemetry-demo                                                                                   Created                                                                                                 0.0s
[+] Running 5/7ometheus                                                                                         Creating                                                                                                0.0s
 ⠿ Network opentelemetry-demo                                                                                                              Created                                                                      0.0s
 ⠿ Container prometheus                                                                                                                    Created                                                                      0.1s
 ⠿ Container grafana                                                                                                                       Created                                                                      0.1s
 ⠿ Container postgres                                                                                                                      Created                                                                      0.1s
 ⠿ Container jaeger                                                                                                                        Created                                                                      0.1s
 ⠙ Container redis-cart                                                                                                                    Creating                                                                     0.1s
 ⠙ Container k8s_kafka_vamsee-otel-demo-kafka-58fb4985c-p8w8r_otel-demo_874de2d4-0209-46c5-b302-232cf2399244_8                             Recreate                                                                     0.1s
 ⠋ Container otel-col                                                                                                                      Creating                                                                     0.0s
 ⠋ Container k8s_featureflagservice_vamsee-otel-demo-featureflagservice-757b95b7f6-mxq6h_otel-demo_02af5af6-08fc-4f25-b151-b0f01dc1bf18_9  Recreate                                                                     0.0s
strconv.Atoi: parsing "": invalid syntax
```

![m1-status](https://user-images.githubusercontent.com/3322496/212496980-bc568335-30d5-4915-bb09-59918875aed1.png)

**Comment by lakamsani** [comment]
` docker-compose down --remove-orphans` fixed the ` docker-compose down --remove-orphans` problem. Thanks to https://stackoverflow.com/questions/73948802/strconv-atoi-parsing-invalid-syntax

**Comment by lakamsani** [comment]
Okay, data is now going to both Lightstep and local Prom/Grafana/Jaeger. The only remaining issue seems to be the feature flag erlang service. Here's some more debug info on that one. Not a serious blocker for what I need to do on my local  M!.

```
 opentelemetry-demo git:(main) k logs vamsee-featureflagservice-56bb949f84-hg58g -n otel-demo
19:55:44.360 [error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table and/or repository for managing migrations:

    config :featureflagservice, Featureflagservice.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations

The full error report is shown below.

** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2986ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (although this increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information

    (ecto_sql 3.8.2) lib/ecto/adapters/sql.ex:932: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.14.2) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.8.2) lib/ecto/adapters/sql.ex:1024: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.8.2) lib/ecto/migrator.ex:696: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.8.2) lib/ecto/migrator.ex:510: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.8.2) lib/ecto/migrator.ex:422: Ecto.Migrator.run/4
    (ecto_sql 3.8.2) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
    nofile:1: (file)
Database setup or migrations failed.


k rollout restart deployment/vamsee-featureflagservice

vamsee-featureflagservice-bd45b7cc7-cdvgc
[vamsee-featureflagservice-bd45b7cc7-cdvgc] 19:57:19.454 [info] Migrations already up

```

**Comment by cartersocha** [comment]
@puckpuck / @tsloughter looks like a db issue from the debug logs. Any thoughts here?

Thanks for sharing the details @lakamsani. We're hoping to produce multiple architecture builds soon. We made some recent progress optimizing build times

**Comment by tsloughter** [comment]
Are there any logs in ffs_postgres?

**Comment by lakamsani** [comment]
```
 ~ k logs vl-otel-demo-ffspostgres-57b458f5c6-k9sqn -n otel-demo
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
syncing data to disk ... ok


Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2023-01-17 04:39:02.447 UTC [35] LOG:  starting PostgreSQL 14.6 (Debian 14.6-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2023-01-17 04:39:02.449 UTC [35] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-01-17 04:39:02.455 UTC [36] LOG:  database system was shut down at 2023-01-17 04:39:01 UTC
2023-01-17 04:39:02.460 UTC [35] LOG:  database system is ready to accept connections
 done
server started
CREATE DATABASE


/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

2023-01-17 04:39:03.172 UTC [35] LOG:  received fast shutdown request
waiting for server to shut down....2023-01-17 04:39:03.179 UTC [35] LOG:  aborting any active transactions
2023-01-17 04:39:03.198 UTC [35] LOG:  background worker "logical replication launcher" (PID 42) exited with exit code 1
2023-01-17 04:39:03.200 UTC [37] LOG:  shutting down
2023-01-17 04:39:03.223 UTC [35] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2023-01-17 04:39:03.306 UTC [1] LOG:  starting PostgreSQL 14.6 (Debian 14.6-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2023-01-17 04:39:03.307 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-01-17 04:39:03.307 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-01-17 04:39:03.310 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-01-17 04:39:03.323 UTC [50] LOG:  database system was shut down at 2023-01-17 04:39:03 UTC
2023-01-17 04:39:03.332 UTC [1] LOG:  database system is ready to accept connections
```

**Comment by mviitane** [comment]
@lakamsani, I recently saw similar `OOMKilled` and `CrashLoopBackOff` problems on x86. In my case, the helm chart values were too restrictive. Increasing the memory in the values file helped, see
https://github.com/open-telemetry/opentelemetry-helm-charts/issues/596

**Comment by lakamsani** [comment]
Hi @mviitane  that seems to resolve it. No more `OMKilled` and `CrashLoopBackOff` when I tried today after rebuilding all the containers to use with Docker Desktop (instead of Rancher). I will try with Rancher later on but I suspect the real issue is indeed the limits. We can close this. Thanks for getting back to me.
